drop_feature:
  [

  ]

class_labels: [
    "class low",
    "class medium",
    "class high",
    "class very high"
  ]

cross_validation_k: 10

train_rate: 0.8

seed: 328

default_lgbm_params:
  task: "train"
  boosting_type: "dart" # "dart" : "gbdt","rf", "goss"
  objective: "multiclass"
  metric: "multi_logloss"
  num_class: 11
  verbose: 0
  num_iterations: 100
  verbose_eval: 5
  device: cpu
  num_threads: 6
  max_bin: 32
  max_depth: 10
